# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Joe Chan'
tagline:          'All Joe Chan, all the time.'
description:      'Joe Chan's personal website'
url:              http://joechan.us

plugins:
  - jekyll-redirect-from

author:
  name:           'Joe Chan'
  url:            https://twitter.com/joech4n

paginate:         5
paginate_path:    "blog/page:num/"

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/joech4n
