# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Joe Chan'
tagline:          'A Jekyll theme'
description:      '<p>Cloud Support Engineer at <a href="http://aws.amazon.com/">Amazon</a>. I like <a href="http://www.apple.com/iphone">tech</a>, <a href="http://bit.ly/league-of-legends">games</a>, playing <a href="https://twitter.com/HistoricalPics/status/464948191063191552/photo/1">basketball</a>, and <a href="http://www.cedarsonbrooklyn.com/">Indian food</a>.</p>'
url:              http://hyde.getpoole.com
profileimg:       http://www.gravatar.com/avatar/62ee1838d7e1d873945c25fede216ebc.jpg

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
