--- 
author: 
  name: "Joe Chan"
  url: "https://twitter.com/joech4n"
description: ""
paginate: 5
paginate_path: "blog/page:num/"
permalink: pretty
plugins: 
  - jekyll-redirect-from
tagline: "All Joe Chan, all the time."
title: "Joe Chan"
url: "http://blog.joechan.us"
version: "2.0.0"
